version: "3"

services:
    LoadBalancer:
        build: Dockerfiles/load-balancer/.
        image: loadbalancer
        container_name: LB
        ports:
            - "80:80"
        depends_on:
            - Syslogserver
        logging:
            driver: syslog
            options:
                syslog-address: "tcp://localhost:514"
                tag: "LB"
        restart: unless-stopped
    Syslogserver:
        build: Dockerfiles/rsyslog/.
        image: syslogserver
        container_name: Syslog
        volumes:
            - "/Users/alessandrobenetton/OneDrive - Cá Foscari - Virtual LABs/University/III_Anno/CT0157-Laboratorio_Amministrazione_Sistema/LAS2021-NGINX-LoadBalancer/Progetto/logs:/var/log"
        ports:
            - 514:514
            - 514:514/udp
        cap_add:
            - SYSLOG
        restart: unless-stopped
